### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by piercegf** [JPBP22/engine#19]
- [ ] Model selector in frontend
- [x] Chatbot (making api call to the openai gpt model)
- [ ] Use a database to store our data (MongoDB).
